/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Controlador.HiloCliente;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.ResourceBundle;


/**
 *
 * @author Manu Romeo
 */
public class InformesComicsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MoviesBoardPanel
     */
    public InformesComicsPanel(HiloCliente h) {
        initComponents();

        /*
        ArrayList<Movie> listaPeliculas = Controller.DBControllerMovies.getMovieList();
        ArrayList<Genre> listaGeneros = Controller.DBControllerMovies.getGenreList();
        txtVerPeliculas.setText("");

        for (Movie pelicula : listaPeliculas) {
            txtVerPeliculas.append(pelicula.toString() + "\n");
        }

        for (Genre genero : listaGeneros) {
            cmbGenero.addItem(genero);
        }
        
        traduccion();
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtVerPeliculas = new javax.swing.JTextArea();
        VerInformeComics = new javax.swing.JButton();
        VerInformeComicsColeccion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(518, 491));

        txtVerPeliculas.setColumns(20);
        txtVerPeliculas.setRows(5);
        jScrollPane2.setViewportView(txtVerPeliculas);

        VerInformeComics.setBackground(new java.awt.Color(0, 102, 204));
        VerInformeComics.setForeground(new java.awt.Color(255, 255, 255));
        VerInformeComics.setText("Ver informe de cómics");
        VerInformeComics.setBorderPainted(false);
        VerInformeComics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInformeComicsActionPerformed(evt);
            }
        });

        VerInformeComicsColeccion.setBackground(new java.awt.Color(0, 102, 204));
        VerInformeComicsColeccion.setForeground(new java.awt.Color(255, 255, 255));
        VerInformeComicsColeccion.setText("Ver informe de cómics por colección");
        VerInformeComicsColeccion.setBorderPainted(false);
        VerInformeComicsColeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInformeComicsColeccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VerInformeComics, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerInformeComicsColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(VerInformeComics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VerInformeComicsColeccion)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VerInformeComicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInformeComicsActionPerformed
       /* String informe = "./src/Informes/InformePeliculas.jrxml";

        try {

            Statement st = Controller.DBConnector.getConexion().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM peliculas.pelicula");

            JRResultSetDataSource dataSource = new JRResultSetDataSource(rs);

            JasperReport report = JasperCompileManager.compileReport(informe);

            JasperPrint visor = JasperFillManager.fillReport(report, null, dataSource);

            JasperViewer.viewReport(visor, false);

        } catch (Exception e) {
        }
*/
    }//GEN-LAST:event_VerInformeComicsActionPerformed

    private void VerInformeComicsColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInformeComicsColeccionActionPerformed
       /* String informe = "./src/Informes/InformePeliculasGenero.jrxml";

        try {

            Genre genero = (Genre) cmbGenero.getSelectedItem();

            PreparedStatement st = Controller.DBConnector.getConexion().prepareStatement("SELECT * FROM peliculas.pelicula WHERE pelicula.idGenero = ?");
            st.setInt(1, genero.getIdGenre());

            ResultSet rs = st.executeQuery();

           
                JRResultSetDataSource dataSource = new JRResultSetDataSource(rs);

                HashMap<String, Object> parametros = new HashMap<>();
                parametros.put("idGenero", genero.getIdGenre());         
                
                System.out.println(parametros.get("idGenero"));
                System.out.println(genero.getIdGenre());
                
                JasperReport report = JasperCompileManager.compileReport(informe);

                JasperPrint visor = JasperFillManager.fillReport(report, parametros, dataSource);

                JasperViewer.viewReport(visor, false);
            

        } catch (Exception e) {
        }
*/
    }//GEN-LAST:event_VerInformeComicsColeccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerInformeComics;
    private javax.swing.JButton VerInformeComicsColeccion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtVerPeliculas;
    // End of variables declaration//GEN-END:variables

     private void traduccion() {

        ResourceBundle rb = ResourceBundle.getBundle("Idiomas.idioma");

        activarTraduccion(rb);

    }

    private void activarTraduccion(ResourceBundle rb) {

        VerInformeComics.setText(rb.getString("VerInformePeliculas"));
        VerInformeComicsColeccion.setText(rb.getString("VerInformePeliculasGenero"));
        

    }
}
